### ISSUE TITLE
Extend a layout from a template located in a sub-directory

### ISSUE THREAD

**Issue by gmosx** [Kitura/Kitura-StencilTemplateEngine#16]
I would like to have the following structure in my Views directory:

```
Views/layout.stencil
Views/index.stencil
Views/users/list.stencil
```

I can extend `layout.stencil` from `index.stencil` using:

```
{% extends "layout.stencil" %}
```

but not from `users/list.stencil`. Both

```
{% extends "../layout.stencil" %}
```

and

```
{% extends "/layout.stencil" %}
```

throw an error:

```
Stencil.SuspiciousFileOperation
```

I think this is a useful/valid use case that I would expect to work.

**Comment by vadimeisenbergibm** [comment]
@gmosx This is the limitation (probably by design) of [Stencil](https://github.com/kylef/Stencil). You may want to open an issue for Stencil, Kitura-StencilTemplateEngine is just an adaptor for Stencil into Kitura framework.

**Comment by kylef** [comment]
The paths given to extend are not relative to the current template, you should be able to use `{% extends "layout.stencil" %}` to achieve the behaviour you are looking for. The search paths for files are inside any configured loaders.

As for the suspicious file operation error, this is because you are trying to escape the file loaders paths. `/layout.stencil` would be on the root of your hard drive and I'd guess you didn't configure the file loader to permit that destination. `../layout.stencil` would be a level up from the file loaders configured destination and thus is escaping the loaders directory.

**Comment by gmosx** [comment]
I think Kitura-Stencil automatically sets the 'root' directory to the base directory of the template file, so this creates this problem, i.e. I cannot just use `{% extends "layout.stencil" %}`

**Comment by vadimeisenbergibm** [comment]
Fixed in Kitura 1.7.4

See example in 
https://github.com/IBM-Swift/Kitura-Sample/blob/master/Sources/KituraSampleRouter/RouterCreator.swift#L210

and the `include` in
https://github.com/IBM-Swift/Kitura-Sample/blob/master/Views/subdirectory/documentInSubdirectory.stencil#L16

It works for `extend` as well.

**Comment by vadimeisenbergibm** [comment]
@gmosx Please try Kitura 1.7.4, see the comment of @kylef  https://github.com/IBM-Swift/Kitura-StencilTemplateEngine/issues/16#issuecomment-304724242. Starting from Kitura 1.7.4, all the paths should be specified relative to the  main Views directory.

**Comment by gmosx** [comment]
Thank you, indeed this change fixes my problem.
